# Generated by Django 4.0.5 on 2022-07-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergy',
            table='allergy',
        ),
        migrations.AlterModelTable(
            name='allergy_drink',
            table='allergy_drink',
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
        migrations.AlterModelTable(
            name='nutrition',
            table='nutritions',
        ),
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
    ]
