# Generated by Django 4.0.5 on 2022-07-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='allergy',
            field=models.ManyToManyField(null=True, to='products.allergy'),
        ),
    ]
