# Generated by Django 4.0.5 on 2022-07-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_allergy_table_alter_allergy_drink_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy_drink',
            old_name='allergy_id',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='allergy_drink',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='size_id',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
