# Generated by Django 4.0.5 on 2022-07-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test_alter_allergy_id_alter_allergy_drink_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
