# Generated by Django 4.0.5 on 2022-07-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
